### ISSUE TITLE
[Off-Topic] O que você ta aprontando com Lisk?

### ISSUE THREAD

**Issue by tloriato** [marcoonroad/ownership-disciplines#2]
To de olho em você, @marcoonroad

**Comment by marcoonroad** [comment]
It's really off-topic, kkkk.

**Comment by marcoonroad** [comment]
:zipper_mouth_face: :innocent:
:see_no_evil: :speak_no_evil: :hear_no_evil:

**Comment by tloriato** [comment]
To vendo voce favoritando tudo do ethereum, abre logo esse repo ai pra eu te ajudar

**Comment by marcoonroad** [comment]
Eu não tenho repo privado no GH não, kkkk. É caro. Pra repo privado eu uso o Bitbucket e GitLab.

**Comment by marcoonroad** [comment]
@tloriato, você descobriu, estou fazendo uma shitcoin. Vou levantar uma ICO, quer ser o primeiro comprador dos meus tokens? :thinking: :moneybag: :bank:

**Comment by tloriato** [comment]
Vai rolar desconto? Se rolar eu compro e aí passo a bola pra frente.

re: muito caro

você é estudante, pode pegar o pacote de estudante de graça :)
